language: python

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

after_success:
  - pip install awscli
  - aws s3 sync public s3://jasonrichardsmith.org/
