baseurl = "http://jasonrichardsmith.org"
title = "Jason Richard Smith"
theme = "hugo-theme-nix"
disqusShortname = "jasonrichardsmithorg"
googleAnalytics = "UA-18788734-3"
[params]
  GithubID = "jasonrichardsmith"
  TwitterID = "@jasonrichardsmi"
  LinkedInID = "jason-smith-62744828"
  Name = "Jason Richard Smith"
  HeaderUsername = "root"
  HeaderHostname = "jasonrichardsmith.org"
  About = "Engineer"
  ProfilePicture = "profile.jpg"
  GoogleAnalytics = "your_google_analytics_id"
[menu]
  [[menu.header]]
    name = "Blog"
    weight = 1
    url = "/blog"
