baseurl = "http://hugojrssite.s3-website-us-west-2.amazonaws.com"
title = "Jason Richard Smith"
theme = "hugo-theme-nix"
[params]
  GithubID = "jasonrichardsmith"
  TwitterID = "@jasonrichardsmi"
  LinkedInID = "jason-smith-62744828"
  Name = "Jason Richard Smith"
  HeaderUsername = "root"
  HeaderHostname = "jasonrichardsmith.org"
  About = "Engineer"
  ProfilePicture = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/07a/24f/0c1356d.jpg"
  GoogleAnalytics = "your_google_analytics_id"
[menu]
  [[menu.header]]
    name = "Skills"
    weight = 0
    url = "/skills"
  [[menu.header]]
    name = "Blog"
    weight = 1
    url = "/blog"
  [[menu.header]]
    name = "Work"
    weight = 2
    url = "/work"
  [[menu.header]]
    name = "Projects"
    weight = 3
    url = "/projects"
